//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBettingSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class bet
    {
        public int id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> theBet { get; set; }
        public Nullable<int> brugerid { get; set; }
        public Nullable<int> wagerid { get; set; }
    
        public virtual Bruger Bruger { get; set; }
        public virtual wager wager { get; set; }
    }
}
