//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBettingSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class wager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wager()
        {
            this.bets = new HashSet<bet>();
        }
    
        public int id { get; set; }
        public double awayOdds { get; set; }
        public double homeOdds { get; set; }
        public double drawOdds { get; set; }
        public Nullable<bool> betOpen { get; set; }
        public Nullable<int> matchid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bet> bets { get; set; }
        public virtual match match { get; set; }
    }
}
